### ISSUE TITLE
Just to get your attention

### ISSUE THREAD

**Issue by sammychinedu2ky** [guardrex/BlazorInRazorPages#1]
Hi @guardrex, I hope you are doing great. Please help me check again if my website is seen as malware using a Malwarebyte.
https://swacblooms.com

**Comment by guardrex** [comment]
Only something called Google Tag Manager. Otherwise, looks great!

![image](https://github.com/guardrex/BlazorInRazorPages/assets/1622880/95f3a5f9-cd6c-456f-b202-aab51e0003f1)

**Comment by sammychinedu2ky** [comment]
Cool thanks so much
